# Generated by Django 4.2.7 on 2025-12-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_deliverycouriers_url_parameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
